In [1]:
import os, sys
import pandas as pd
from glob import glob

In [2]:
path = os.getcwd()
temp = path.split("/")[:-1]
temp.append("data/*/*.csv")
# print(temp)
path_to_data = "/".join(temp ) 
print (path_to_data )

/Users/barradd/Documents/GitHub/machine_learning_chem_RGS/data/*/*.csv

In [3]:
all_dataframe=[]
for file in glob(path_to_data):
    df_temp=pd.read_csv(file)
    all_dataframe.append(df_temp)

In [4]:
df_pubchem = pd.concat(all_dataframe, axis=0)

In [5]:
df_pubchem.head()

,cid,molecular_formula,molecular_weight,exact_mass,monoisotopic_mass,charge,heavy_atom_count,h_bond_donor_count,h_bond_acceptor_count,xlogp,...,P,S,F,Se,Cl,Br,Si,Ge,B,As
0,116550634,C11H15NO2,193.24,193.110279,193.110279,0,14,1,3,1.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,55284015,C7H7NO,121.14,121.052764,121.052764,0,9,1,2,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,115978707,C11H15NO2,193.24,193.110279,193.110279,0,14,3,3,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,13319560,C7H7NO,121.14,121.052764,121.052764,0,9,0,2,0.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,132494532,C7H7NO,121.14,121.052764,121.052764,0,9,1,2,-0.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
resolved_cid  = df_pubchem["cid"].unique()

In [7]:
resolved_cid.shape

(223617,)

In [8]:
type(resolved_cid.tolist())

list

In [9]:
cids_to_search = [ int(x) for x in open("../data/compunds_cids.txt").readlines() ]

In [10]:
len ( cids_to_search) -  resolved_cid.shape[0]

793

In [11]:
resolved_cid = set ( resolved_cid.tolist() ) 
cids_to_search = set ( cids_to_search )

In [13]:
difference_cid = cids_to_search - resolved_cid

In [14]:
len ( difference_cid )

31

In [15]:
# out_file = open("../data/missing_cids.txt","w")
# for id in difference_cid:
#     out_file.write(str(id)+"\n")
# out_file.close()

In [16]:
path = '/Users/barradd/Documents/GitHub/machine_learning_chem_RGS/data/inital-data-19-nov-23.xlsx'

In [17]:
my_df = pd.read_excel(path)

In [18]:
my_df.head()

,substituent,molecular formula,Name,Î”VC-m,Î”VC -p,Ïƒm,Ïƒp,Fb,Rc
0,SO2CN,C7H5NO2S,Benzenesulfonyl cyanide,27.007403,28.300000,1.10,1.26,0.97,0.29
1,C(CN)=C(CN)2,C11H5N3,"2-phenylethene-1,1,2-tricarbonitrile",24.873869,27.000000,0.77,0.98,0.65,0.33
2,SO2F,C6H5FO2S,benzenesulfonyl fluoride,24.270832,25.381524,0.80,0.91,0.72,0.19
3,SO2Cl,C6H5ClO2S,benzenesulfonyl chloride,24.246359,25.200000,1.20,1.11,1.16,-0.05
4,C(NO2)3,C7H5N3O6,Trinitromethylbenzene,23.556098,25.100000,0.72,0.82,0.65,0.17

In [19]:
my_df.columns

Index(['substituent', 'molecular formula', 'Name', 'Î”VC-m', 'Î”VC -p', 'Ïƒm',
       'Ïƒp', 'Fb', 'Rc'],
      dtype='object')

In [20]:
my_df.columns = ['substituent', 'molecular_formula', 'Name', 'Î”VC-m', 'Î”VC -p', 'Ïƒm','Ïƒp', 'Fb', 'Rc']

In [21]:
df_merged = pd.merge(left=my_df,right=df_pubchem,on="molecular_formula")

In [22]:
df_merged.head()

,substituent,molecular_formula,Name,Î”VC-m,Î”VC -p,Ïƒm,Ïƒp,Fb,Rc,cid,...,P,S,F,Se,Cl,Br,Si,Ge,B,As
0,SO2CN,C7H5NO2S,Benzenesulfonyl cyanide,27.007403,28.3,1.1,1.26,0.97,0.29,45099325,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SO2CN,C7H5NO2S,Benzenesulfonyl cyanide,27.007403,28.3,1.1,1.26,0.97,0.29,14749846,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SO2CN,C7H5NO2S,Benzenesulfonyl cyanide,27.007403,28.3,1.1,1.26,0.97,0.29,13086207,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SO2CN,C7H5NO2S,Benzenesulfonyl cyanide,27.007403,28.3,1.1,1.26,0.97,0.29,54546756,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SO2CN,C7H5NO2S,Benzenesulfonyl cyanide,27.007403,28.3,1.1,1.26,0.97,0.29,54004786,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df_merged.tail()

,substituent,molecular_formula,Name,Î”VC-m,Î”VC -p,Ïƒm,Ïƒp,Fb,Rc,cid,...,P,S,F,Se,Cl,Br,Si,Ge,B,As
319015,N(Et)2,C10H15N,Diethylaniline,-6.313378,-11.9,-0.23,-0.72,0.01,-0.73,113633,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319016,N(Et)2,C10H15N,Diethylaniline,-6.313378,-11.9,-0.23,-0.72,0.01,-0.73,84763164,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319017,N(Et)2,C10H15N,Diethylaniline,-6.313378,-11.9,-0.23,-0.72,0.01,-0.73,12480996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319018,N(Et)2,C10H15N,Diethylaniline,-6.313378,-11.9,-0.23,-0.72,0.01,-0.73,130637333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319019,N(Et)2,C10H15N,Diethylaniline,-6.313378,-11.9,-0.23,-0.72,0.01,-0.73,129313663,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
from datetime import date
today = date.today()
print ( "Today's date:", today)

Today's date: 2023-12-04

In [25]:
df_merged.to_excel(f"../data/pubchem_data_{today}.xlsx", index=False )

In [26]:
df_merged.to_csv(f"../data/pubchem_data_{today}.csv", index=False)